"""EFEM player data source adapter.

Loads player data from EFEM API JSON files (data/raw/efeme/*.json)
and converts them to canonical Player objects.
"""

import json
import os
from collections.abc import AsyncIterator
from pathlib import Path
from typing import Optional

from src.backend.services.player_data_source import Player, PlayerDataSource


# Map EFEM primary nationality name → Country code
# This ensures we always use the correct ISO code for the player
EFEM_NATIONALITY_TO_CODE = {
    "Argentina": "ARG",
    "Algeria": "ALG",
    "Australia": "AUS",
    "Austria": "AUT",
    "Belgium": "BEL",
    "Bosnia and Herzegovina": "BIH",
    "Brazil": "BRA",
    "Cabo Verde": "CPV",
    "Canada": "CAN",
    "Colombia": "COL",
    "Congo": "COD",  # Democratic Republic of Congo (from EFEM API)
    "Croatia": "CRO",
    "Curacao": "CUW",
    "Czechia": "CZE",
    "Côte d'Ivoire": "CIV",
    "Ecuador": "ECU",
    "Egypt": "EGY",
    "England": "ENG",
    "France": "FRA",
    "Germany": "GER",
    "Ghana": "GHA",
    "Haiti": "HAI",
    "Iran": "IRN",
    "Iraq": "IRQ",
    "Japan": "JPN",
    "Jordan": "JOR",
    "South Korea": "KOR",
    "Mexico": "MEX",
    "Morocco": "MAR",
    "Netherlands": "NED",
    "New Zealand": "NZL",
    "Norway": "NOR",
    "Panama": "PAN",
    "Paraguay": "PAR",
    "Portugal": "POR",
    "Qatar": "QAT",
    "Saudi Arabia": "KSA",
    "Scotland": "SCO",
    "Senegal": "SEN",
    "South Africa": "RSA",
    "Spain": "ESP",
    "Sweden": "SWE",
    "Switzerland": "SUI",
    "Tunisia": "TUN",
    "Turkey": "TUR",
    "United States": "USA",
    "Uruguay": "URU",
    "Uzbekistan": "UZB",
}

# Map EFEM position proficiency → simplified position
POS_MAP = {
    "GK": "GK",
    "CB": "DEF", "RB": "DEF", "LB": "DEF", "RWB": "DEF", "LWB": "DEF", "DF": "DEF",
    "CDM": "MID", "CM": "MID", "CAM": "MID", "RM": "MID", "LM": "MID", "MF": "MID",
    "RW": "FWD", "LW": "FWD", "ST": "FWD", "CF": "FWD", "FW": "FWD",
}


def _extract_position_from_proficiency(position_proficiency: dict) -> tuple[str, str]:
    """Extract simplified and detailed positions from EFEM position proficiency dict.
    
    Args:
        position_proficiency: Dict mapping position code (e.g., "rw", "cm") to proficiency score.
    
    Returns:
        (simplified_pos, detailed_pos_string)
    """
    if not position_proficiency:
        return "MID", "CM"
    
    # Sort by proficiency descending to find primary position
    sorted_positions = sorted(position_proficiency.items(), key=lambda x: x[1], reverse=True)
    primary = sorted_positions[0][0].upper()
    
    # Build detailed string from top positions (score > 0)
    top_positions = [pos.upper() for pos, score in sorted_positions if score > 30]
    detailed = ", ".join(top_positions) if top_positions else primary
    
    simplified = POS_MAP.get(primary, "MID")
    return simplified, detailed


def _convert_market_value(efem_player: dict) -> int:
    """Get market value from EFEM data.
    
    Uses recommendedBuyPrice (estimated fair market value).
    Falls back to askingPrice if recommendedBuyPrice is 0.
    """
    recommended = efem_player.get("recommendedBuyPrice", 0) or 0
    if recommended > 0:
        return int(recommended)
    
    asking = efem_player.get("askingPrice", 0) or 0
    return int(asking)


class EFEMPlayerDataSource(PlayerDataSource):
    """EFEM API JSON player data source.
    
    Loads players from EFEM format JSON files generated by import_efeme_players.py
    and converts them to canonical Player objects.
    """
    
    def __init__(self, data_dir: str = "data/raw/efeme"):
        self.data_dir = Path(data_dir)
    
    async def load_all_players(self) -> list[Player]:
        """Load all players from EFEM JSON files."""
        players = []
        
        if not self.data_dir.exists():
            print(f"[WARN] EFEM data directory not found: {self.data_dir}")
            return players
        
        json_files = sorted([f for f in self.data_dir.glob("*.json") 
                            if not f.name.startswith("_") and 
                            f.name not in ("import_status.json", "README.md")])
        
        print(f"[DATA] Loading EFEM players from {len(json_files)} country files...")
        
        for filepath in json_files:
            try:
                with open(filepath, "r", encoding="utf-8") as f:
                    data = json.load(f)
                
                country_name = data.get("country", "Unknown")
                source_info = data.get("source", {})
                players_data = data.get("players", [])
                
                # Get country code from first player's nationCode or fallback
                country_code = self._get_country_code(country_name, source_info, players_data)
                if not country_code:
                    print(f"  [WARN] Skipping {filepath.name}: Unknown country '{country_name}'")
                    continue
                
                extracted_at = data.get("extracted_at")
                
                for player_data in players_data:
                    try:
                        player = self._convert_player(
                            player_data, country_code, country_name, extracted_at
                        )
                        players.append(player)
                    except Exception as e:
                        print(f"  [WARN] Error converting player: {e}")
                        continue
                
                print(f"  [OK] {filepath.name}: {len(players_data)} players")
            
            except Exception as e:
                print(f"  [ERR] Error loading {filepath.name}: {e}")
                continue
        
        print(f"[OK] Total: {len(players)} players loaded from EFEM")
        return players
    
    def _get_json_files(self) -> list[Path]:
        """Get sorted list of country JSON files."""
        if not self.data_dir.exists():
            return []
        return sorted([f for f in self.data_dir.glob("*.json") 
                       if not f.name.startswith("_") and 
                       f.name not in ("import_status.json", "README.md")])
    
    async def load_players_by_country(self) -> AsyncIterator[list[Player]]:
        """Yield players one country at a time to limit memory usage."""
        json_files = self._get_json_files()
        if not json_files:
            print("[WARN] EFEM data directory not found or empty")
            return
        
        print(f"[DATA] Streaming EFEM players from {len(json_files)} country files...")
        
        for filepath in json_files:
            try:
                with open(filepath, "r", encoding="utf-8") as f:
                    data = json.load(f)
                
                country_name = data.get("country", "Unknown")
                source_info = data.get("source", {})
                players_data = data.get("players", [])
                
                country_code = self._get_country_code(country_name, source_info, players_data)
                if not country_code:
                    print(f"  [WARN] Skipping {filepath.name}: Unknown country '{country_name}'")
                    continue
                
                extracted_at = data.get("extracted_at")
                batch = []
                
                for player_data in players_data:
                    try:
                        player = self._convert_player(
                            player_data, country_code, country_name, extracted_at
                        )
                        batch.append(player)
                    except Exception as e:
                        continue
                
                print(f"  [OK] {filepath.name}: {len(batch)} players")
                yield batch
                # batch goes out of scope, memory freed
                
            except Exception as e:
                print(f"  [ERR] Error loading {filepath.name}: {e}")
                continue
    
    def _get_country_code(self, country_name: str, source_info: dict, players_data: list) -> Optional[str]:
        """Get country code from first player's nationCode, source metadata, or country name."""
        # Best source: first player's primaryNationality.nationCode
        if players_data:
            first_player = players_data[0]
            if isinstance(first_player, dict):
                primary = first_player.get("primaryNationality", {})
                if isinstance(primary, dict):
                    nation_code = primary.get("nationCode")
                    if nation_code:
                        return nation_code
        
        # Fallback: effective_filter_term in EFEM_NATIONALITY_TO_CODE
        if source_info:
            filter_term = source_info.get("effective_filter_term", "")
            if filter_term in EFEM_NATIONALITY_TO_CODE:
                return EFEM_NATIONALITY_TO_CODE[filter_term]
        
        # Fallback: direct country name lookup
        if country_name in EFEM_NATIONALITY_TO_CODE:
            return EFEM_NATIONALITY_TO_CODE[country_name]
        
        return None
    
    def _convert_player(
        self, player_data: dict, country_code: str, country_name: str, extracted_at: str
    ) -> Player:
        """Convert an EFEM player JSON object to canonical Player object."""
        
        player_id = player_data.get("id", "")
        player_obj_id = f"{country_code}-{player_id}"
        
        # Extract position from positionProficiency (dict: pos_code → score)
        position_proficiency = player_data.get("positionProficiency", {})
        if not isinstance(position_proficiency, dict):
            position_proficiency = {}
        position, detailed_position = _extract_position_from_proficiency(position_proficiency)
        
        # Extract nationality - can be dict or string
        primary_nationality = player_data.get("primaryNationality", {})
        if isinstance(primary_nationality, dict):
            nationality_code = primary_nationality.get("nationCode", country_code)
        else:
            nationality_code = country_code
        
        if nationality_code:
            country_code = nationality_code
        
        # Extract roles (dict: role_name → score)
        roles_data = player_data.get("roles", {})
        if isinstance(roles_data, dict):
            roles = [name for name, score in sorted(roles_data.items(), key=lambda x: x[1], reverse=True) if score > 70]
        else:
            roles = None
        
        # Extract positions (dict: pos_code → score)
        positions_data = player_data.get("positions", {})
        if isinstance(positions_data, dict):
            positions = [pos.upper() for pos, score in sorted(
                ((k, v) for k, v in positions_data.items() if not k.startswith("max")),
                key=lambda x: x[1], reverse=True
            ) if score > 50]
        else:
            positions = None
        
        # Use top-level numeric attributes directly
        overall = player_data.get("currentAbility", 50) or 50
        
        # Physical sub-attributes for pace
        physical_attr = player_data.get("physicalAttribute", {})
        pace = physical_attr.get("pace") if isinstance(physical_attr, dict) else None
        
        # Estimate market value from EFEM data
        market_value = _convert_market_value(player_data)
        
        # Contract info
        contract_expiry = player_data.get("contractExpiryDate")
        wage_per_week = int(player_data.get("wagePerWeek", 0) or 0)
        release_clause = int(player_data.get("releaseClause", 0) or 0)
        
        # Image URL pattern for EFEM
        player_image = f"https://d2utsopg4ciewu.cloudfront.net/{player_id}.png"
        
        return Player(
            id=player_obj_id,
            name=player_data.get("name", "Unknown"),
            country_code=country_code,
            position=position,
            detailed_position=detailed_position,
            roles=roles if roles else None,
            club=player_data.get("clubName", ""),
            league="",
            age=player_data.get("age", 0) or 0,
            market_value=market_value,
            contract_expiry=contract_expiry,
            wage_per_week=wage_per_week,
            release_clause=release_clause,
            strength=max(0, min(99, overall)),
            pace=pace,
            shooting=player_data.get("shooting"),
            passing=player_data.get("playmaking"),
            dribbling=player_data.get("ballControl"),
            defending=player_data.get("defending"),
            physic=player_data.get("physical"),
            efem_score=player_data.get("efemScore"),
            current_ability=player_data.get("currentAbility"),
            potential_ability=player_data.get("maxPotentialAbility"),
            positions=positions if positions else None,
            photo_url=player_image,
            source="efem",
            extracted_at=extracted_at,
        )
    
    def get_source_name(self) -> str:
        return "EFEM API JSON"
